Revert "kms: Fix warning XNFprintf is deprecated"
This reverts commit cb4dc7ab66016d0c980800f8dbf71bbe993889d3.

Looks like this caused https://bugs.freedesktop.org/attachment.cgi?id=43852 ,
but even if it didn't, the following needs to be addressed first:

cc1: warnings being treated as errors
../../src/radeon_kms.c: In function ‘radeon_open_drm_master’:
../../src/radeon_kms.c:413: error: passing argument 1 of ‘XNFasprintf’ from incompatible pointer type
/usr/local/include/xorg/Xprintf.h:57: note: expected ‘char **’ but argument is of type ‘char *’
../../src/radeon_kms.c:413: error: passing argument 2 of ‘XNFasprintf’ makes pointer from integer without a cast
/usr/local/include/xorg/Xprintf.h:57: note: expected ‘const char * restrict’ but argument is of type ‘uint16_t’
../../src/radeon_kms.c:413: error: assignment makes pointer from integer without a cast
make[2]: *** [radeon_kms.lo] Error 1