Partially revert "kms: wait for fbcon to be copied before continuing"
This partially reverts commit 6c045fc44783454180d7b3d00b5f25436bd5544e.

The nv_driver.c hunk of the above patch breaks the build on at least git
and 1.6.3.901 xorg-servers due to:
nv_driver.c:745: error: 'struct _ScrnInfoRec' has no member named
'canDoBGNoneRoot'

Signed-off-by: Pekka Paalanen <pq@iki.fi>